version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-134-25.compute-1.amazonaws.com
            port: '5432'
            database: d4lu4g8r14e2oo
            ssl: true
            user: imvwmkjrrzxapg
            password: 717a52580314b8bf9a396ab195c652fa5dcf76c9d92bf62d216f39b60b154450
            migrations: true